# sb_project_config.yaml
tools:
  - ConFuzzius
  - Conkas
  - Manticore
  - Osiris
  - Mythril
  - Oyente
  - sFuzz
  - Slither
  - Smartcheck

files:
  - "cobra-plus-dataset/*.sol"

processes: 4
timeout: 600
mem-limit: 4g
json: true